accessible_restaurant/accessible_restaurant/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('restaurants/', include('restaurants.urls')),
    path('admin/', admin.site.urls),
]

accessible_restaurant/restaurants/urls.py
from django.urls import path

from . import views

app_name = 'restaurants'
urlpatterns = [
    # ex: /register/
    path('register/', views.index, name='index'),
]

accessible_restaurant/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
from .forms import UserLoginForm, MyPasswordResetForm

# from .forms import PickyAuthenticationForm

app_name = "accessible_restaurant"
urlpatterns = [
    path("", views.index_view_personalized, name="index"),
    # path("about/", views.about_view, name="about"),
    path(
        "accounts/login",
        auth_views.LoginView.as_view(
            template_name="accounts/signin.html",
            authentication_form=UserLoginForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "accounts/logout",
        auth_views.LogoutView.as_view(template_name="index.html"),
        name="logout",
    ),
    path(
        "accounts/password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/passwordReset.html",
            # form_class=PickyAuthenticationForm,
            form_class=MyPasswordResetForm,
        ),
        name="password-reset",
    ),
    path("accounts/signup/", views.signup_view, name="signup"),
    path(
        "accounts/signup/usersignup/",
        views.UserSignUpView.as_view(),
        name="user_signup",
    ),
    path(
        "accounts/signup/restaurantsignup/",
        views.RestaurantSignUpView.as_view(),
        name="restaurant_signup",
    ),
    path("accounts/signup/emailsent/", views.emailsent_view, name="emailsent"),
    path("accounts/<uidb64>/<token>", views.activate_account, name="activate"),
    # Profile urls
    path("accounts/user-profile/", views.user_profile_view, name="user_profile"),
    path(
        "accounts/restaurant-profile/",
        views.restaurant_profile_view,
        name="restaurant_profile",
    ),
    # Browse restaurant
    # <sort_property>/
    path(
        "restaurants/browse/<page>/",
        views.restaurant_list_view,
        name="browse",
    ),
    path(
        "restaurants/detail/<business_id>", views.restaurant_detail_view, name="detail"
    ),
    # Review and comments
    path("writeareview/<business_id>", views.write_review_view, name="write_review"),
    path(
        "restaurants/detail/<business_id>/<review_id>/",
        views.add_comment_view,
        name="add_comment",
    ),
    path("user_detail/<user>", views.user_detail_view, name="public_facing"),
    # admin manage the certificate
    path("manage/", views.authentication_view, name="authenticate"),
    # Frequently Asked Questions
    path("faq/", views.faq_view, name="faq"),
]

nyc_accessible_restaurant_advisor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from accessible_restaurant.forms import MySetPasswordForm

urlpatterns = [
    path("", include("accessible_restaurant.urls")),
    path("admin/", admin.site.urls),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/passwordResetConfirm.html",
            form_class=MySetPasswordForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("accounts/", include("allauth.urls")),
]


# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accessible_restaurant/restaurants/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
# Create your views here.

def index(request):
    return render(request, 'restaurants/register.html')
    # return "Hello World!"
    # template = loader.get_template('restaurants/index.html')
    # return HttpResponse(template.render(request))
    # return HttpResponse("Hello, world. You're at the polls index.")

accessible_restaurant/views.py
from sqlite3 import Error

from django.core.exceptions import FieldDoesNotExist
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.shortcuts import redirect

# from django.contrib import messages
from django.views.generic import CreateView
from django.http import HttpResponse, HttpResponseNotFound
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings

# from .token_generator import generate_token
from django.core.mail import EmailMessage

from django.db.models import Q

from .forms import (
    UserSignUpForm,
    RestaurantSignUpForm,
    UserUpdateForm,
    UserProfileUpdateForm,
    UserPreferencesForm,
    RestaurantProfileUpdateForm,
    ReviewPostForm,
    UserCertUpdateForm,
    UserCertVerifyForm,
    RestaurantCertUpdateForm,
    RestaurantCertVerifyForm,
    CommentForm,
    ContactForm,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from .models import (
    User,
    Restaurant,
    Review,
    ApprovalPendingUsers,
    ApprovalPendingRestaurants,
    User_Profile,
    User_Preferences,
    Restaurant_Profile,
    FAQ,
    Favorites,
    # Images,
)
from .utils import (
    get_restaurant_list,
    get_filter_restaurant,
    get_restaurant,
    get_page_range,
    get_star_list,
    get_search_restaurant,
    get_public_user_detail,
    get_user_reviews,
    get_user_preferences,
    get_user_favorite,
    get_user_profile_favorite,
)

from django.forms import modelformset_factory

# Create your views here.
# def index_view(request):
#     recommended_restaurants = Restaurant.objects.all()[:3]
#     context = {"recommended_restaurants": recommended_restaurants}
#     return render(request, "home.html", context)


def index_view_personalized(request):
    try:
        if request.user.is_user:
            user = request.user
            recommended_restaurants = get_user_preferences(user)[:3]
        else:
            temp = (
                Restaurant.objects.all()
                .filter(
                    Q(review_count__gt=20)
                    & Q(rating__gte=4.0)
                    & Q(compliant__exact=True)
                )
                .order_by("-rating")
            )
            recommended_restaurants = temp[:3]
    except (
        TypeError,
        ValueError,
        AttributeError,
    ):
        temp = (
            Restaurant.objects.all()
            .filter(
                Q(review_count__gt=20) & Q(rating__gte=4.0) & Q(compliant__exact=True)
            )
            .order_by("-rating")
        )
        recommended_restaurants = temp[:3]
    context = {"recommended_restaurants": recommended_restaurants}
    return render(request, "home.html", context)


# def about_view(request):
#     return render(request, "accounts/about.html")


@login_required
def logout_view(request):
    return render(request, "accounts/logout.html")


def signup_view(request):
    if request.method == "GET":
        return render(request, "accounts/signup.html")


def emailsent_view(request):
    if request.method == "GET":
        return render(request, "accounts/emailSent.html")


def activate_account(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
        # print(user.username)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and PasswordResetTokenGenerator().check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, "accounts/activate_confirmation.html")
    return render(request, "accounts/register.html")


class UserSignUpView(CreateView):
    model = User
    form_class = UserSignUpForm
    template_name = "accounts/userSignup.html"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "user"
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        # check if user's email has already exist in the database
        user_email = form.cleaned_data.get("email")
        if User.objects.filter(email=user_email).exists():
            return render(
                self.request,
                self.template_name,
                {
                    "error_message": "Email has already been registered.",
                    "form": form,
                },
            )
        user = form.save()
        user.is_active = False
        user.save()
        # Email verification
        current_site = get_current_site(self.request)
        email_subject = "Activate Your NYC Accessible Restaurant Advisor Account!"
        message = render_to_string(
            "accounts/activate_account.html",
            {
                "user": user,
                "domain": current_site.domain,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": PasswordResetTokenGenerator().make_token(user),
            },
        )
        to_email = form.cleaned_data.get("email")
        email = EmailMessage(email_subject, message, to=[to_email])
        email.send()
        return redirect("accessible_restaurant:emailsent")


class RestaurantSignUpView(CreateView):
    model = User
    form_class = RestaurantSignUpForm
    template_name = "accounts/restaurantSignup.html"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "restaurant"
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        # check if restaurant's email has already exist in the database
        restaurant_email = form.cleaned_data.get("email")
        if User.objects.filter(email=restaurant_email).exists():
            return render(
                self.request,
                self.template_name,
                {
                    "error_message": "Email has already been registered.",
                    "form": form,
                },
            )
        restaurant = form.save()
        restaurant.is_active = False
        restaurant.save()
        # Email verification
        current_site = get_current_site(self.request)
        email_subject = "Activate Your NYC Accessible Restaurant Advisor Account!"
        message = render_to_string(
            "accounts/activate_account.html",
            {
                "user": restaurant,
                "domain": current_site.domain,
                "uid": urlsafe_base64_encode(force_bytes(restaurant.pk)),
                "token": PasswordResetTokenGenerator().make_token(restaurant),
            },
        )
        to_email = form.cleaned_data.get("email")
        email = EmailMessage(email_subject, message, to=[to_email])
        email.send()
        return redirect("accessible_restaurant:emailsent")


@login_required
@user_passes_test(lambda u: u.is_user, login_url="/", redirect_field_name=None)
def user_profile_view(request):
    if request.method == "POST":
        if "submit-certificate" in request.POST:
            auth_form = UserCertUpdateForm(request.POST, request.FILES)
            if auth_form.is_valid():
                tmp_auth = auth_form.save(commit=False)
                tmp_auth.user = request.user
                tmp_auth.auth_status = "pending"
                prev_auth_len = ApprovalPendingUsers.objects.filter(
                    user=request.user
                ).count()
                if prev_auth_len > 0:
                    prev_auth = ApprovalPendingUsers.objects.get(user=request.user)
                    prev_auth.auth_documents.delete()
                    prev_auth.delete()
                auth_form.save()
                p_instance = User_Profile.objects.get(user=request.user)
                p_instance.auth_status = "pending"
                p_instance.save()
                messages.success(
                    request, f'{"Your certificate has been sent to administrator!"}'
                )
                return redirect("accessible_restaurant:user_profile")
            else:
                u_form = UserUpdateForm(instance=request.user)
                p_form = UserProfileUpdateForm(instance=request.user.uprofile)
                preferences_form = UserPreferencesForm(
                    instance=request.user.upreferences
                )

        elif "submit-info" in request.POST:
            u_form = UserUpdateForm(request.POST, instance=request.user)
            p_form = UserProfileUpdateForm(
                request.POST, request.FILES, instance=request.user.uprofile
            )
            preferences_form = UserPreferencesForm(instance=request.user.upreferences)
            if u_form.is_valid() and p_form.is_valid():
                u_form.save()
                p_form.save()
                messages.success(request, f'{"Your profile has been updated!"}')
                return redirect("accessible_restaurant:user_profile")
            else:
                queue = ApprovalPendingUsers.objects.filter(user=request.user).count()
                if queue > 0:
                    q = ApprovalPendingUsers.objects.get(user=request.user)
                    auth_form = UserCertUpdateForm(instance=q.user.auth)
                else:
                    auth_form = UserCertUpdateForm()

        elif "submit-preferences" in request.POST:
            preferences_form = UserPreferencesForm(
                request.POST, request.FILES, instance=request.user.upreferences
            )
            u_form = UserUpdateForm(instance=request.user)

accessible_restaurant/templates/publicface/public_profile.html
{% extends "baseheader.html" %}
{% load crispy_forms_tags %}

{% block staticlink %}
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'accessible_restaurant/public_profile_style.css' %}">
    <script src="https://kit.fontawesome.com/6a247440d5.js" crossorigin="anonymous"></script>
{% endblock %}

{% block title %} Public User Profile {% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="content" id="content">
                    <div class="profile">
                        <div class="profile-header">
                            <div class="profile-header-cover"></div>
                            <div class="profile-header-content">
                                <div class="col-md-2 profile-header-img">
                                    <img src="{{ photo.url }}" alt="">
                                </div>
                                <div class="col-md-8 profile-header-info">
                                    <h4 class="m-2">{{ username }}</h4>
                                    {% if city or state %}
                                        <p class="m-2">{{ city }} {{ state }}</p>
                                    {% else %}
                                        <p class="m-2">No address info</p>
                                    {% endif %}
                                </div>
                            </div>
                            <ul class="profile-header-tab nav nav-tabs">
                                <li class="nav-item"><a href="#profile-review" class="nav-link active show" data-toggle="tab">RELATED REVIEWS</a></li>
                                <li class="nav-item"><a href="#profile-favorite" class="nav-link" data-toggle="tab">FAVORITE RESTAURANTS</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="profile-content">
                        <div class="tab-content p-0">
                            <div class="tab-pane fade active show" id="profile-review">
                                <ul class="timeline">
                                    {% for review in user_review %}
                                        <li>
                                            <div class="timeline-time">
                                                <span class="date">{{ review.review_date | date:"Y-m-d" }}</span>
                                                <span class="time">{{ review.review_date | date:"H:i" }}</span>
                                            </div>
                                            <div class="timeline-icon">
                                                <a>&nbsp;</a>
                                            </div>
                                            <div class="timeline-body">
                                                <div class="timeline-header">
                                                    <span class="restimage"><img src="{{ review.res_url }}" alt=""></span>
                                                    <span class="username"><a href="{% url 'accessible_restaurant:detail' review.business_id %}">{{ review.res_name }}</a> <small></small></span>
                                                </div>
                                                <div class="timeline-content">
                                                    <p>{{ review.review_context }}</p>
                                                </div>
                                                <div class="timeline-likes">
                                                    <div class="stats-right">
                                                        <span class="stats-text">{{ review.comments_count }} Comments</span>
                                                    </div>
                                                    <ul class="list-inline">
                                                        {% for _ in review.full %}
                                                            <li class="list-inline-item">
                                                                <i class="icon-star-full fas fa-star"></i>
                                                            </li>
                                                        {% endfor %}
                                                        {% for _ in review.half %}
                                                            <li class="list-inline-item">
                                                                <i class="icon-star-half fas fa-star-half-alt"></i>
                                                            </li>
                                                        {% endfor %}
                                                        {% for _ in review.null %}
                                                            <li class="list-inline-item">
                                                                <i class="icon-star-null far fa-star"></i>
                                                            </li>
                                                        {% endfor %}
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}

                                    <li>
                                        <div class="timeline-icon">
                                            <a>&nbsp;</a>
                                        </div>
                                        <div class="timeline-body">
                                            No more reviews...
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="tab-pane fade" id="profile-favorite">
                                {% for restaurant in user_favorite %}
                                    <div class="row d-flex justify-content-center">
                                        <div class="col-10">
                                            <div class="m-2 mt-4">
                                                <div class="card mb-2">
                                                    <div class="row no-gutters">
                                                        <div class="col-4 align-self-center">
                                                            <img src="{{ restaurant.img_url }}" class="card-img m-4" alt="...">
                                                        </div>
                                                        <div class="col-8">
                                                            <div class="card-body mx-4">
                                                                {% if restaurant.compliant %}
                                                                    <h5 class="card-title">{{ restaurant.name }}&emsp;<span class="badge badge-pill badge-success">Compliant <i class="fas fa-wheelchair" aria-hidden="true"></i></span></h5>
                                                                {% else %}
                                                                    <h5 class="card-title">{{ restaurant.name }}&emsp;<span class="badge badge-pill badge-secondary">Not Compliant <i class="fas fa-wheelchair" aria-hidden="true"></i></span></h5>
                                                                {% endif %}
                                                                <p class="card-text">
                                                                    <ul class="list-inline">
                                                                        {% for _ in restaurant.full %}
                                                                            <li class="list-inline-item">
                                                                                <i class="icon-star-full fas fa-star"></i>
                                                                            </li>
                                                                        {% endfor %}
                                                                        {% for _ in restaurant.half %}
                                                                            <li class="list-inline-item">
                                                                                <i class="icon-star-half fas fa-star-half-alt"></i>
                                                                            </li>
                                                                        {% endfor %}
                                                                        {% for _ in restaurant.null %}
                                                                            <li class="list-inline-item">
                                                                                <i class="icon-star-null far fa-star"></i>
                                                                            </li>
                                                                        {% endfor %}
                                                                    </ul>
                                                                    <large class="text-muted">{{ restaurant.price }} {{ restaurant.category1 }} {{ restaurant.category2 }} {{ restaurant.category3 }}</large>
                                                                </p>
                                                                <p class="card-text">
                                                                    <ul>
                                                                        <li><i class="phone-icon fas fa-phone-square-alt"></i>&emsp;{{ restaurant.phone }}</li>
                                                                        <li><i class="address-icon fas fa-map-marker-alt"></i>&emsp;{{ restaurant.address }}, {{ restaurant.city }}, {{ restaurant.zip_code }}</li>
                                                                    </ul>
                                                                </p>
                                                                <a href="{% url 'accessible_restaurant:detail' restaurant.business_id %}" class="btn btn-light">Details</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}