accessible_restaurant/accessible_restaurant/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('restaurants/', include('restaurants.urls')),
    path('admin/', admin.site.urls),
]

accessible_restaurant/restaurants/urls.py
from django.urls import path

from . import views

app_name = 'restaurants'
urlpatterns = [
    # ex: /register/
    path('register/', views.index, name='index'),
]

accessible_restaurant/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
from .forms import UserLoginForm, MyPasswordResetForm

# from .forms import PickyAuthenticationForm

app_name = "accessible_restaurant"
urlpatterns = [
    path("", views.index_view_personalized, name="index"),
    # path("about/", views.about_view, name="about"),
    path(
        "accounts/login",
        auth_views.LoginView.as_view(
            template_name="accounts/signin.html",
            authentication_form=UserLoginForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "accounts/logout",
        auth_views.LogoutView.as_view(template_name="index.html"),
        name="logout",
    ),
    path(
        "accounts/password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/passwordReset.html",
            # form_class=PickyAuthenticationForm,
            form_class=MyPasswordResetForm,
        ),
        name="password-reset",
    ),
    path("accounts/signup/", views.signup_view, name="signup"),
    path(
        "accounts/signup/usersignup/",
        views.UserSignUpView.as_view(),
        name="user_signup",
    ),
    path(
        "accounts/signup/restaurantsignup/",
        views.RestaurantSignUpView.as_view(),
        name="restaurant_signup",
    ),
    path("accounts/signup/emailsent/", views.emailsent_view, name="emailsent"),
    path("accounts/<uidb64>/<token>", views.activate_account, name="activate"),
    # Profile urls
    path("accounts/user-profile/", views.user_profile_view, name="user_profile"),
    path(
        "accounts/restaurant-profile/",
        views.restaurant_profile_view,
        name="restaurant_profile",
    ),
    # Browse restaurant
    # <sort_property>/
    path(
        "restaurants/browse/<page>/",
        views.restaurant_list_view,
        name="browse",
    ),
    path(
        "restaurants/detail/<business_id>", views.restaurant_detail_view, name="detail"
    ),
    # Review and comments
    path("writeareview/<business_id>", views.write_review_view, name="write_review"),
    path(
        "restaurants/detail/<business_id>/<review_id>/",
        views.add_comment_view,
        name="add_comment",
    ),
    path("user_detail/<user>", views.user_detail_view, name="public_facing"),
    # admin manage the certificate
    path("manage/", views.authentication_view, name="authenticate"),
    # Frequently Asked Questions
    path("faq/", views.faq_view, name="faq"),
]

nyc_accessible_restaurant_advisor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from accessible_restaurant.forms import MySetPasswordForm

urlpatterns = [
    path("", include("accessible_restaurant.urls")),
    path("admin/", admin.site.urls),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/passwordResetConfirm.html",
            form_class=MySetPasswordForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("accounts/", include("allauth.urls")),
]


# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accessible_restaurant/restaurants/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
# Create your views here.

def index(request):
    return render(request, 'restaurants/register.html')
    # return "Hello World!"
    # template = loader.get_template('restaurants/index.html')
    # return HttpResponse(template.render(request))
    # return HttpResponse("Hello, world. You're at the polls index.")

accessible_restaurant/views.py
from sqlite3 import Error

from django.core.exceptions import FieldDoesNotExist
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.shortcuts import redirect

# from django.contrib import messages
from django.views.generic import CreateView
from django.http import HttpResponse, HttpResponseNotFound
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings

# from .token_generator import generate_token
from django.core.mail import EmailMessage

from django.db.models import Q

from .forms import (
    UserSignUpForm,
    RestaurantSignUpForm,
    UserUpdateForm,
    UserProfileUpdateForm,
    UserPreferencesForm,
    RestaurantProfileUpdateForm,
    ReviewPostForm,
    UserCertUpdateForm,
    UserCertVerifyForm,
    RestaurantCertUpdateForm,
    RestaurantCertVerifyForm,
    CommentForm,
    ContactForm,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from .models import (
    User,
    Restaurant,
    Review,
    ApprovalPendingUsers,
    ApprovalPendingRestaurants,
    User_Profile,
    User_Preferences,
    Restaurant_Profile,
    FAQ,
    Favorites,
    # Images,
)
from .utils import (
    get_restaurant_list,
    get_filter_restaurant,
    get_restaurant,
    get_page_range,
    get_star_list,
    get_search_restaurant,
    get_public_user_detail,
    get_user_reviews,
    get_user_preferences,
    get_user_favorite,
    get_user_profile_favorite,
)

from django.forms import modelformset_factory

# Create your views here.
# def index_view(request):
#     recommended_restaurants = Restaurant.objects.all()[:3]
#     context = {"recommended_restaurants": recommended_restaurants}
#     return render(request, "home.html", context)


def index_view_personalized(request):
    try:
        if request.user.is_user:
            user = request.user
            recommended_restaurants = get_user_preferences(user)[:3]
        else:
            temp = (
                Restaurant.objects.all()
                .filter(
                    Q(review_count__gt=20)
                    & Q(rating__gte=4.0)
                    & Q(compliant__exact=True)
                )
                .order_by("-rating")
            )
            recommended_restaurants = temp[:3]
    except (
        TypeError,
        ValueError,
        AttributeError,
    ):
        temp = (
            Restaurant.objects.all()
            .filter(
                Q(review_count__gt=20) & Q(rating__gte=4.0) & Q(compliant__exact=True)
            )
            .order_by("-rating")
        )
        recommended_restaurants = temp[:3]
    context = {"recommended_restaurants": recommended_restaurants}
    return render(request, "home.html", context)


# def about_view(request):
#     return render(request, "accounts/about.html")


@login_required
def logout_view(request):
    return render(request, "accounts/logout.html")


def signup_view(request):
    if request.method == "GET":
        return render(request, "accounts/signup.html")


def emailsent_view(request):
    if request.method == "GET":
        return render(request, "accounts/emailSent.html")


def activate_account(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
        # print(user.username)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and PasswordResetTokenGenerator().check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, "accounts/activate_confirmation.html")
    return render(request, "accounts/register.html")


class UserSignUpView(CreateView):
    model = User
    form_class = UserSignUpForm
    template_name = "accounts/userSignup.html"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "user"
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        # check if user's email has already exist in the database
        user_email = form.cleaned_data.get("email")
        if User.objects.filter(email=user_email).exists():
            return render(
                self.request,
                self.template_name,
                {
                    "error_message": "Email has already been registered.",
                    "form": form,
                },
            )
        user = form.save()
        user.is_active = False
        user.save()
        # Email verification
        current_site = get_current_site(self.request)
        email_subject = "Activate Your NYC Accessible Restaurant Advisor Account!"
        message = render_to_string(
            "accounts/activate_account.html",
            {
                "user": user,
                "domain": current_site.domain,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": PasswordResetTokenGenerator().make_token(user),
            },
        )
        to_email = form.cleaned_data.get("email")
        email = EmailMessage(email_subject, message, to=[to_email])
        email.send()
        return redirect("accessible_restaurant:emailsent")


class RestaurantSignUpView(CreateView):
    model = User
    form_class = RestaurantSignUpForm
    template_name = "accounts/restaurantSignup.html"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "restaurant"
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        # check if restaurant's email has already exist in the database
        restaurant_email = form.cleaned_data.get("email")
        if User.objects.filter(email=restaurant_email).exists():
            return render(
                self.request,
                self.template_name,
                {
                    "error_message": "Email has already been registered.",
                    "form": form,
                },
            )
        restaurant = form.save()
        restaurant.is_active = False
        restaurant.save()
        # Email verification
        current_site = get_current_site(self.request)
        email_subject = "Activate Your NYC Accessible Restaurant Advisor Account!"
        message = render_to_string(
            "accounts/activate_account.html",
            {
                "user": restaurant,
                "domain": current_site.domain,
                "uid": urlsafe_base64_encode(force_bytes(restaurant.pk)),
                "token": PasswordResetTokenGenerator().make_token(restaurant),
            },
        )
        to_email = form.cleaned_data.get("email")
        email = EmailMessage(email_subject, message, to=[to_email])
        email.send()
        return redirect("accessible_restaurant:emailsent")


@login_required
@user_passes_test(lambda u: u.is_user, login_url="/", redirect_field_name=None)
def user_profile_view(request):
    if request.method == "POST":
        if "submit-certificate" in request.POST:
            auth_form = UserCertUpdateForm(request.POST, request.FILES)
            if auth_form.is_valid():
                tmp_auth = auth_form.save(commit=False)
                tmp_auth.user = request.user
                tmp_auth.auth_status = "pending"
                prev_auth_len = ApprovalPendingUsers.objects.filter(
                    user=request.user
                ).count()
                if prev_auth_len > 0:
                    prev_auth = ApprovalPendingUsers.objects.get(user=request.user)
                    prev_auth.auth_documents.delete()
                    prev_auth.delete()
                auth_form.save()
                p_instance = User_Profile.objects.get(user=request.user)
                p_instance.auth_status = "pending"
                p_instance.save()
                messages.success(
                    request, f'{"Your certificate has been sent to administrator!"}'
                )
                return redirect("accessible_restaurant:user_profile")
            else:
                u_form = UserUpdateForm(instance=request.user)
                p_form = UserProfileUpdateForm(instance=request.user.uprofile)
                preferences_form = UserPreferencesForm(
                    instance=request.user.upreferences
                )

        elif "submit-info" in request.POST:
            u_form = UserUpdateForm(request.POST, instance=request.user)
            p_form = UserProfileUpdateForm(
                request.POST, request.FILES, instance=request.user.uprofile
            )
            preferences_form = UserPreferencesForm(instance=request.user.upreferences)
            if u_form.is_valid() and p_form.is_valid():
                u_form.save()
                p_form.save()
                messages.success(request, f'{"Your profile has been updated!"}')
                return redirect("accessible_restaurant:user_profile")
            else:
                queue = ApprovalPendingUsers.objects.filter(user=request.user).count()
                if queue > 0:
                    q = ApprovalPendingUsers.objects.get(user=request.user)
                    auth_form = UserCertUpdateForm(instance=q.user.auth)
                else:
                    auth_form = UserCertUpdateForm()

        elif "submit-preferences" in request.POST:
            preferences_form = UserPreferencesForm(
                request.POST, request.FILES, instance=request.user.upreferences
            )
            u_form = UserUpdateForm(instance=request.user)

accessible_restaurant/templates/accounts/activate_account.html
{% autoescape off %}

Hi {{ user.username }},

Please click this link below to verify your account!
http://{{ domain }}{% url 'accessible_restaurant:activate' uidb64=uid token=token %}

Best,
NYC Accessible Restaurant Advisor Team
{% endautoescape %}

accessible_restaurant/templates/accounts/activate_confirmation.html
{% extends "baseheader.html" %}

{% block staticlink %}
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'accessible_restaurant/signup_style.css' %}">
    <script src="https://kit.fontawesome.com/6a247440d5.js" crossorigin="anonymous"></script>
{% endblock %}

{% block title %} Email Activate Confirmation {% endblock %}

{% block content %}
    <div class="container content">
        <!-- Verification Email Link Jumbotron -->
        <div class="row h-100 align-items-center justify-content-center">
            <div class="col-md-12">
                <div class="jumbotron text-center">
                    <h2>Activation Success! <a href="{% url 'accessible_restaurant:login' %}">Log In Here</a></h2>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accessible_restaurant/templates/accounts/login.html
{% extends "base.html" %}

{% block staticlink %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accessible_restaurant/register_style.css' %}">
{% endblock %}

{% block title %} Login Form {% endblock %}

{% block body %}<body class="subpage">{% endblock %}

{% block content %}
    <div class="wrapper fl">
        <div class="main">
            <div class="head">
                <p>Login Form</p>
            </div>
            {% load crispy_forms_tags %}
            <div class="form fl">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="submit-wrap">
                        <input type="submit" id="submit" name="sb" value="SUBMIT">
                    </div>
                    <p><a href="{% url 'accessible_restaurant:password-reset' %}">Forgot Password?</a></p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accessible_restaurant/templates/accounts/passwordReset.html
{% extends "baseheader.html" %}
{% load crispy_forms_tags %}

{% block staticlink %}
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'accessible_restaurant/signin_style.css' %}">
    <script src="https://kit.fontawesome.com/6a247440d5.js" crossorigin="anonymous"></script>
{% endblock %}

{% block title %} Reset Password Request {% endblock %}

{% block content %}
    <div class="container content">
        <div class="row h-100 align-items-center justify-content-center">
            <div class="col-8 d-flex align-items-center">
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        {% if form.non_field_errors %}
                            <div class="col-lg-12">
                                <div class="alert alert-danger alert-dismissible fade show">
                                    <strong>{{ form.non_field_errors|escape }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            </div>
                        {% endif %}

                        <!-- Email Address -->
                        <div class="input-group col-lg-12 mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-envelope text-muted"></i>
                                </span>
                            </div>
    <!--                        <input id="email" type="email" name="email" placeholder="Email Address" class="form-control bg-white border-left-0 border-md">-->
                            {{ form.email }}
                        </div>
                        {% for error in form.email.errors %}
                            <div class="col-lg-12">
                                <div class="alert alert-danger alert-dismissible fade show">
                                    <strong>{{ error|escape }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            </div>
                        {% endfor %}

                        <!-- Submit Button -->
                        <div class="form-group col-lg-12 mx-auto mb-0">
                            <input type="submit" id="submit" name="submit" value="Request Reset" class="btn btn-primary btn-block py-2 font-weight-bold">
<!--                            <a href="#" class="btn btn-primary btn-block py-2">-->
<!--                                <span class="font-weight-bold">Request Reset</span>-->
<!--                            </a>-->
                        </div>

                        <!-- Divider Text -->
                        <div class="form-group col-lg-12 mx-auto d-flex align-items-center my-4">
                            <div class="border-bottom w-100 ml-5"></div>
                            <span class="px-2 small text-muted font-weight-bold text-muted">OR</span>
                            <div class="border-bottom w-100 mr-5"></div>
                        </div>

                        <!-- Not Registered -->
                        <div class="text-center w-100">
                            <p class="text-muted font-weight-bold">Remember Password? <a href="{% url 'accessible_restaurant:login' %}" class="text-primary ml-2">Login</a></p>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accessible_restaurant/templates/accounts/register.html
{% extends "base.html" %}

{% block staticlink %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accessible_restaurant/banner_style.css' %}">
{% endblock %}

{% block title %} Registration {% endblock %}

{% block content %}
<section id="banner">
    <div class="inner">
        <header>
            <h1>Welcome to NYC Accessible Restaurant Advisor</h1>
        </header>

        <div class="flex ">
            <div>
                <h3><a href="{% url 'accessible_restaurant:user_signup' %}">As a User</a></h3>
                <p>Write Review/Leave Feedback</p>
            </div>

            <div>
                <h3><a href="{% url 'accessible_restaurant:browse' 0 %}">Just Browsing</a></h3>
                <p>Search</p>
            </div>

            <div>
                <h3><a href="{% url 'accessible_restaurant:restaurant_signup' %}">As a Restaurant</a></h3>
                <p>Post info/Connect with customer</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accessible_restaurant/templates/accounts/request_received.html
{% autoescape off %}

Hi there,

We have received your feedback and suggestion. Thank you so much for helping us improve our service.

Your Subject : {{ subject }}
Your Message : {{ message }}

Best,
NYC Accessible Restaurant Advisor Team
{% endautoescape %}

accessible_restaurant/templates/accounts/signin.html
{% extends "baseheader.html" %}
{% load crispy_forms_tags %}

{% block staticlink %}
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'accessible_restaurant/signin_style.css' %}">
    <script src="https://kit.fontawesome.com/6a247440d5.js" crossorigin="anonymous"></script>
{% endblock %}

{% block title %} Login {% endblock %}

{% block content %}
    <div class="container content">
        <div class="row h-100 align-items-center justify-content-center">
            <div class="col-8 d-flex align-items-center">
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        {% if form.non_field_errors %}
                            <div class="col-lg-12">
                                <div class="alert alert-danger alert-dismissible fade show">
                                    <strong>{{ form.non_field_errors|escape }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            </div>
                        {% endif %}
                        <!-- Username -->
                        <div class="input-group col-lg-12 mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-user text-muted"></i>
                                </span>
                            </div>
<!--                            <input id="username" type="text" name="username" placeholder="Username" class="form-control bg-white border-left-0 border-md">-->
                            {{ form.username }}
                        </div>
                        {% for error in form.username.errors %}
                            <div class="col-lg-12">
                                <div class="alert alert-danger alert-dismissible fade show">
                                    <strong>{{ error|escape }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            </div>
                        {% endfor %}

                        <!-- Password -->
                        <div class="input-group col-lg-12 mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-lock text-muted"></i>
                                </span>
                            </div>
<!--                            <input id="password" type="password" name="password" placeholder="Password" class="form-control bg-white border-left-0 border-md">-->
                            {{ form.password }}
                        </div>
                        {% for error in form.password.errors %}
                            <div class="col-lg-12">
                                <div class="alert alert-danger alert-dismissible fade show">
                                    <strong>{{ error|escape }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            </div>
                        {% endfor %}

                        <div class="text-center w-100">
                            <p class="text-muted font-weight-bold">Forget Password? <a href="{% url 'accessible_restaurant:password-reset' %}" class="text-primary ml-2">Reset</a></p>
                        </div>

                        <!-- Submit Button -->
                        <div class="form-group col-lg-12 mx-auto mb-0">
                            <input type="submit" id="submit" name="submit" value="Login" class="btn btn-primary btn-block py-2 font-weight-bold">
<!--                            <a href="#" class="btn btn-primary btn-block py-2">-->
<!--                                <span class="font-weight-bold">Login</span>-->
<!--                            </a>-->
                        </div>

                        <!-- Divider Text -->
                        <div class="form-group col-lg-12 mx-auto d-flex align-items-center my-4">
                            <div class="border-bottom w-100 ml-5"></div>
                            <span class="px-2 small text-muted font-weight-bold text-muted">OR</span>
                            <div class="border-bottom w-100 mr-5"></div>
                        </div>

                        <!-- Social Login -->
                        {% load socialaccount %}
                        <input type='hidden' name='csrfmiddlewaretoken' value='{{ csrf_token }}' />
                        <div class="form-group col-lg-12 mx-auto">
                            <a href="{% provider_login_url 'facebook' process='login' action='reauthenticate' %}" class="btn btn-primary btn-block py-2 btn-facebook">
                                <i class="fa fa-facebook-f mr-2"></i>
                                <span class="font-weight-bold">Continue with Facebook</span>
                            </a>
                            <a href="{% provider_login_url 'google' process='login' action='reauthenticate' %}" class="btn btn-primary btn-block py-2 btn-google">
                                <i class="fab fa-google mr-2"></i></i>
                                <span class="font-weight-bold">Continue with Google</span>
                            </a>
                        </div>

                        <!-- Not Registered -->
                        <div class="text-center w-100">
                            <p class="text-muted font-weight-bold">Not Registered? <a href="{% url 'accessible_restaurant:signup' %}" class="text-primary ml-2">Register</a></p>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}